# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-01-21 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price Unit')),
                ('volume_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Volume Unit')),
                ('weight_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Weight Unit')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
    ]
