# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-01-23 13:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_auto_20240123_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalname',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MaxLengthValidator(20, message='Name cannot exceed 20 characters')], verbose_name='Name'),
        ),
    ]
