# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-01-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_auto_20240123_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalname',
            name='lunar_day',
            field=models.CharField(default='01', max_length=2, verbose_name='Lunar Day'),
        ),
        migrations.AlterField(
            model_name='festivalname',
            name='lunar_month',
            field=models.CharField(default='01', max_length=2, verbose_name='Lunar Month'),
        ),
    ]
