# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-01-23 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0007_festalitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FestalItems',
            new_name='FestivalItems',
        ),
    ]
