# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-01-23 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0007_festivalitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festivalitems',
            old_name='created_time',
            new_name='create_time',
        ),
    ]
