# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-01-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0008_auto_20240123_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last5YearsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('enable', models.BooleanField(default=True, verbose_name='Enabled')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('product_id', models.ManyToManyField(to='configs.AbstractProduct', verbose_name='Product ID')),
                ('source', models.ManyToManyField(to='configs.Source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Last5YearsItems',
            },
        ),
        migrations.AlterModelOptions(
            name='festivalitems',
            options={'ordering': ('order_sn',), 'verbose_name': 'Festival Item'},
        ),
    ]
