# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-05-10 09:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email_dns', models.CharField(max_length=255, validators=[django.core.validators.URLValidator], verbose_name='Email Dns')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='auth.Group', verbose_name='Group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.GroupInformation', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Group Information',
                'verbose_name_plural': 'Group Informations',
            },
        ),
    ]
